version: '3.8'

services:
    app-be:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    app-fe:
        image: node:20
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        ports:
            - "5173:5173" # Vite's default port
        command: sh -c "npm install && npm run dev"
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: cottage-cms
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
